secret:
  # -- whether to generate user secret
  enabled: false
  data_:
    # -- user authorization, if empty, random value is generated
    ServiceAuth: ""
deployment:
  # -- Docker image
  image: tidepool/platform-user:master-latest
  replicas: 1
resources: {}
podSecurityContext: {}
podAnnotations: {}
securityContext: {}
hpa:
  # -- whether to create a horizontal pod autoscalers for all pods of given deployment
  enabled: false
  # -- minimum number of replicas that HPA will maintain
  minReplicas: 1
  # -- maximum number of replicas that HPA will maintain
  maxReplicas: null
pdb:
  enabled: false
  minAvailable: "50%"
mongo:
  secretName: mongo
nodeSelector: {}
tolerations: []
affinity: {}
