iamRole: ""
secret:
  # -- whether to create image secret
  enabled: false
  data_:
    # -- plaintext service authorization secret
    ServiceAuth: ""
deployment:
  # -- Docker image
  image: tidepool/platform-image:master-latest
  replicas: 1
  env:
    store:
      file:
        # -- directory to use when storing images on file storage
        directory: "_data/image"
        prefix: "images"
      s3:
        # -- S3 bucket where image data is written
        bucket:  "data"
        # -- file prefix to use when storing images on file storage
        prefix: "images"
      # -- if `s3`, store image data in Amazon S3. If `file` store image data in local file
      type: file
      #type: s3
resources: {}
podSecurityContext: {}
podAnnotations: {}
securityContext: {}
serviceAccount:
  create: false
hpa:
  # -- whether to create a horizontal pod autoscalers for all pods of given deployment
  enabled: false
  # -- minimum number of replicas that HPA will maintain
  minReplicas: 1
  # -- maximum number of replicas that HPA will maintain
  maxReplicas: null
pdb:
  enabled: false
  minAvailable: "50%"
mongo:
  secretName: mongo
nodeSelector: {}
tolerations: []
affinity: {}
