secret:
  # -- whether to create blob secret
  enabled: false
  data_:
    # -- plaintext service authorization secret
    ServiceAuth: ""
deployment:
  replicas: 1
  # -- default Docker image
  image: tidepool/platform-blob:master-latest
  env:
    store:
      s3:
        # -- S3 bucket where blob data is written
        bucket: "data"
        prefix: "blobs"
      file:
        prefix: "blobs"
        # -- directory to use when storing blobs on file storage
        directory: "_data/blobs" 
      # -- if `s3`, store blob data in Amazon S3. If `file` store blob data in local files.
      type: file
resources: {}
podSecurityContext: {}
podAnnotations: {}
securityContext: {}
serviceAccount:
  create: false
hpa:
  # -- whether to create a horizontal pod autoscalers for all pods of given deployment
  enabled: false
  # -- minimum number of replicas that HPA will maintain
  minReplicas: 1
  # -- maximum number of replicas that HPA will maintain
  maxReplicas: null
pdb:
  enabled: false
  minAvailable: "50%"
mongo:
  secretName: mongo
nodeSelector: {}
tolerations: []
affinity: {}
