configmap:
  enabled: true
  EmailsTopic: "emails"
  Brokers: "kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
  RequireSSL: true
  TopicPrefix: ""
  UserEventsTopic: "user-events"
  UserEventsShorelineDeadLettersTopic: "user-events-shoreline-dl"
  UserEventsMarketoDeadLettersTopic: "user-events-marketo-dl"
  Version: "2.4.0"
nodeSelector: {}
tolerations: []
affinity: {}
