{{ if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "charts.labels.standard" . }}
data:
  Brokers: {{ .Values.configmap.Brokers }}
{{ if .Values.configmap.TopicPrefix }}
  TopicPrefix: {{ .Values.configmap.TopicPrefix }}
{{ else }}
  TopicPrefix: "{{ .Release.Namespace }}-"
{{ end }}
  EmailsTopic: {{ .Values.configmap.EmailsTopic }}
  UserEvent: {{ .Values.configmap.UserEvent | default "events" }}
  Version: {{ .Values.configmap.Version | default "2.4.0" }}
  SSL: {{ .Values.configmap.SSL | default true }}
  ConsumerGroup: {{ .Values.configmap.ConsumerGroup }}
{{ end }}
