configmap:
  enabled: false
  data:
    ClinicDemoUserId: ""
secret:
  enabled: false
  data_:
    # -- service authorization secret
    ServiceAuth: ""
    UserLongTermKey:
    UserMailVerification: ""
    ClinicDemoUserId: ""
deployment:
  # -- Docker image
  image: tidepool/shoreline:master-latest
  replicas: 1
resources: {}
podSecurityContext: {}
podAnnotations: {}
securityContext: {}
serviceMonitor:
  enabled: false
hpa:
  # -- whether to create a horizontal pod autoscalers for all pods of given deployment
  enabled: false
  # -- minimum number of replicas that HPA will maintain
  minReplicas: 1
  # -- maximum number of replicas that HPA will maintain
  maxReplicas: null
pdb:
  enabled: false
  minAvailable: "50%"
mongo:
  secretName: mongo
nodeSelector: {}
tolerations: []
affinity: {}
