secret:
  enabled: false
  data_:
    ServiceAuth: ""
    AppleDeviceCheckKey: ""
configmap:
  data_:
    AppleDeviceCheckKeyIssuer: "75U4X84TEG"
    AppleDeviceCheckKeyId: "B542R658GF"
    AppleDeviceCheckUseDevelopment: "true"
deployment:
  # -- auth Docker image
  image: tidepool/platform-auth:master-latest
  replicas: 1
resources: {}
initContainers: []
podSecurityContext: {}
podAnnotations: {}
securityContext: {}
hpa:
  # -- whether to create a horizontal pod autoscalers for all pods of given deployment
  enabled: false
  # -- minimum number of replicas that HPA will maintain
  minReplicas: 1
  # -- maximum number of replicas that HPA will maintain
  maxReplicas: null
pdb:
  enabled: false
  minAvailable: "50%"
mongo:
  secretName: mongo
nodeSelector: {}
tolerations: []
affinity: {}
